### ISSUE TITLE
Discord-linux app dose not open

### ISSUE THREAD

**Issue by medchedli** [XNBlank/discord-linux#25]
`A JavaScript error occurred in the main process
Uncaught Exception:
TypeError: Cannot read property 'minTray' of undefined
    at Object.<anonymous> (/usr/local/bin/discord-linux-x64/resources/app/main.js:22:17)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Object.<anonymous> (/usr/local/bin/discord-linux-x64/resources/atom.asar/browser/lib/init.js:123:10)
    at Object.<anonymous> (/usr/local/bin/discord-linux-x64/resources/atom.asar/browser/lib/init.js:125:4)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
`

**Comment by XNBlank** [comment]
Please check `~/.config/Discord/` for an `init.json` file. If it does not exist, create it and paste this inside
`{"bounds":{"x":0,"y":26,"width":1920,"height":1025},"minTray":false,"useCSS":false}`

**Comment by jacobmischka** [comment]
If it doesn't exist the program should handle it. Are you sure you're on the newest build? 

Based on that log it looks like you aren't.

[This](https://github.com/XNBlank/discord-linux/blob/01488dc175727d5f83434a8919800a0735634096/resources/app/main.js#L22) is where you're crashing, and that line [doesn't exist anymore](https://github.com/XNBlank/discord-linux/blob/master/resources/app/main.js).
